# GHC 8.0.2 has a bug, which may leads to OOM
# https://ghc.haskell.org/trac/ghc/ticket/13615
resolver: lts-14.27
# setup-info:
#   ghc:
#     linux64-custom-dwarf-tinfo6:
#       8.4.4:
#         url: https://downloads.haskell.org/~ghc/8.4.4/ghc-8.4.4-x86_64-deb9-linux-dwarf.tar.xz
# ghc-variant: dwarf
ghc-options:
    "$everything": -threaded
packages:
- .
- ../fei-base/
- ../tuple-ops
extra-deps:
- git: https://github.com/0xCM/type-combinators.git
  commit: 58167dd4017b666ff592bb9493b0570a054aabdb
- git: https://github.com/pierric/haskell-src-exts.git
  commit: f75a5dbe2ec9fbc67df0936333e0665b033f9e22
- streaming-utils-0.1.4.7
- graphviz-2999.20.0.4
extra-include-dirs:
- /home/jiasen/workspace/mxnet/build-1.6.0/include
extra-lib-dirs:
- /home/jiasen/workspace/mxnet/build-1.6.0
flags:
  fei-base:
    mxnet_geq_10600: true
  fei-nn:
    mxnet_geq_10600: true
