# GHC 8.0.2 has a bug, which may leads to OOM
# https://ghc.haskell.org/trac/ghc/ticket/13615
resolver: lts-10.7
packages:
- .
extra-deps:
- git: https://github.com/pierric/mxnet-haskell.git
  commit: afd0aa747e3a5f9229e7658e0776596b1243bd6e
  subdirs:
  - mxnet
- c2hs-extra-0.1.0.1
- tuple-ops-0.0.0.1
- streaming-utils-0.1.4.7
allow-newer: true
extra-include-dirs:
- /home/jwu/incubator-mxnet/include
- /home/jwu/incubator-mxnet/nnvm/include/
extra-lib-dirs:
- /home/jwu/incubator-mxnet/lib
