# GHC 8.0.2 has a bug, which may leads to OOM
# https://ghc.haskell.org/trac/ghc/ticket/13615
resolver: lts-12.26
# setup-info:
#   ghc:
#     linux64-custom-dwarf-tinfo6:
#       8.4.4:
#         url: https://downloads.haskell.org/~ghc/8.4.4/ghc-8.4.4-x86_64-deb9-linux-dwarf.tar.xz
# ghc-variant: dwarf
ghc-options:
    "$everything": -threaded
packages:
- .
extra-deps:
- ../fei-base/
- ../tuple-ops
- git: https://github.com/kylcarte/type-combinators.git
  commit: 071942730b6bb34990d37e1a25236382cf0dcbc6
- git: https://github.com/pierric/haskell-src-exts.git
  commit: f75a5dbe2ec9fbc67df0936333e0665b033f9e22
- c2hs-extra-0.1.0.1
- streaming-utils-0.1.4.7
- graphviz-2999.20.0.2
- fgl-5.5.4.0
- unordered-containers-0.2.10.0
extra-include-dirs:
- /home/jiasen/dschungel/incubator-mxnet-1.5/include
- /home/jiasen/dschungel/incubator-mxnet-1.5/nnvm/include/
extra-lib-dirs:
- /home/jiasen/dschungel/incubator-mxnet-1.5/lib
flags:
  fei-base:
    MXNet_1_5: true
