name: mxnet
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.15.4=py36h7e9f1db_0
  - python=3.6
  - pip:
    - click==7.0
    - mxnet-cu100==1.5.0b20181206
    - netron==2.7.2
    - onnx==1.3.0
